### ISSUE TITLE
Move from Mailchimp to something elese

### ISSUE THREAD

**Issue by DanielMSchmidt** [DanielMSchmidt/workshopManager#12]
As Mailchimp is now paid and this is a free service. For alternatives see here: https://www.reddit.com/r/webdev/comments/47frgs/mandrill_is_becoming_a_paid_addon_for_monthly/d0cyy0k

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.

The free plan is 100,000 emails/month.

**Comment by DanielMSchmidt** [comment]
@yepher Wow, awesome, thanks for your help.

**Comment by yepher** [comment]
Sure, check into the Slack channel if you have any questions.
